### ISSUE TITLE
.NET SDK of Sync Api not correctly deserializing JSON

### ISSUE THREAD

**Issue by selmiskr** [kontent-ai/delivery-sdk-net#383]
### Brief bug description

When sync api recognizes changes and we try to retrieve the changes with the help of the .NET SDK we get an empty response back.
But when we look at the JSON of the response, we are noticing that the entire data is correctly there.

We suspect that the deserialization of the JSON item to the ISyncItem is not correctly done.

### Screenshots

![image (1)](https://github.com/kontent-ai/delivery-sdk-net/assets/8503234/9c09146d-da23-45c8-8f4f-71d15134c505)
![image (2)](https://github.com/kontent-ai/delivery-sdk-net/assets/8503234/983ae509-c872-4561-b92c-01144933750b)

**Comment by pokornyd** [comment]
the model differed from the API response format, without mapping implemented to account for that. I adjusted the model to match [sync API response](https://kontent.ai/learn/docs/apis/openapi/sync-api/#operation/synchronize-changes-in-content-items), content item information is now nested in `Data` property.

a strongly typed item can be retrieved from newly introduced `StronglyTypedData` property, as long as a `TypeProvider` is registered and can found a suitable model. the property is `null` otherwise
